### ISSUE TITLE
假设你提到这种方式比较好用

### ISSUE THREAD

**Issue by Pillar1989** [mzr1996/backbone-example#1]
假设你提到这种方式比较好用，那为什么你们官方的mmcls，mmdet，mmseg这些项目不使用这种方式，而是每个项目单独拉出来搞 ？

或者能否列举通过这种方式复现相关论文或者工程化的案例 ？

**Comment by mzr1996** [comment]
主要参考
https://github.com/ZwwWayne/K-Net

**Comment by mzr1996** [comment]
另外，这里是用于第三方实现某个具体功能（如主干网络）的推荐方式，而官方仓库旨在维护某一任务需要的功能，两者并不存在重叠，实际上 mim 就是在自动调用各个仓库提供的 API。

**Comment by Pillar1989** [comment]
好的，谢谢
