### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [256, 96, 1, 1], expected input[4, 128, 200, 200] to have 96 channels, but got 128 channels instead

### ISSUE THREAD

**Issue by sanmulab** [mzr1996/backbone-example#2]
My some configs:

_base_ = [
    '../_base_/models/cascade_rcnn_r50_fpn.py'
]

pretrained='./pretrained_model/convnext-base_3rdparty_32xb128_in1k.pth'
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)

model = dict(
    type='CascadeRCNN',
    backbone=dict(
        _delete_=True,
        type='mmcls.ConvNeXt',
        arch='base',
        out_indices=[0, 1, 2, 3],
        drop_path_rate=0.5,
        layer_scale_init_value=1.0,
        gap_before_final_norm=False,
        init_cfg=dict(
            type='Pretrained', checkpoint=pretrained)),
    neck=dict(
        type='FPN',
        in_channels=[96, 192, 384, 768],
        out_channels=256,
        num_outs=5),

But meet a error:RuntimeError: Given groups=1, weight of size [256, 96, 1, 1], expected input[4, 128, 200, 200] to have 96 channels, but got 128 channels instead

**Comment by mzr1996** [comment]
The `in_channels` of FPN is not align with the output of `ConvNeXt`, please check it, the output channels of ConvNeXt-base should be [128, 256, 512, 1024]

**Comment by sanmulab** [comment]
That's OK. Thank you!
